#!/bin/bash

touch /config/cron

# convert crlf and add newline
tr -d '\r' < /config/cron > /tmp/cron
echo >> /tmp/cron

# set crontab and echo
crontab /tmp/cron
crontab -l

mkfifo /tmp/stdout /tmp/stderr
chmod 0666 /tmp/stdout /tmp/stderr

tail -f /tmp/stdout &
tail -f /tmp/stderr >&2 &